-- =============================================================
-- SEED: GlowUp Aesthetics — Botox & Med Spa Clinic
-- Business ID: 0cc1fd6d-cf1e-40ec-8483-a093900d35bb
-- Run in Supabase Studio > SQL Editor
-- Safe to re-run (deletes existing data first)
-- Generates 100 services + 100 staff
-- =============================================================

DO $$
DECLARE
  uid UUID;
  bid UUID;
BEGIN

-- Look up the user and their business
SELECT id INTO uid FROM auth.users WHERE email = 'usmanarif.9219@gmail.com';
IF uid IS NULL THEN
  RAISE EXCEPTION 'User usmanarif.9219@gmail.com not found in auth.users';
END IF;

SELECT id INTO bid FROM public.businesses WHERE owner_id = uid;
IF bid IS NULL THEN
  RAISE EXCEPTION 'No business found for user usmanarif.9219@gmail.com';
END IF;

-- =============================================================
-- 1. UPDATE BUSINESS PROFILE
-- =============================================================
UPDATE businesses SET
  name       = 'GlowUp Aesthetics',
  type       = 'Botox & Med Spa Clinic',
  contact    = '+1 (310) 555-8800',
  address    = '1200 Wilshire Blvd, Suite 450, Beverly Hills, CA 90210',
  updated_at = now()
WHERE id = bid;

-- =============================================================
-- 2. CLEAR OLD DATA (order matters — children before parents)
-- =============================================================
DELETE FROM chat_messages  WHERE session_id IN (SELECT id FROM chat_sessions WHERE business_id = bid);
DELETE FROM chat_sessions  WHERE business_id = bid;
DELETE FROM appointments   WHERE business_id = bid;
DELETE FROM staff_hours    WHERE business_id = bid;
DELETE FROM staff_custom_fields WHERE business_id = bid;
DELETE FROM staff          WHERE business_id = bid;
DELETE FROM service_custom_fields WHERE business_id = bid;
DELETE FROM services       WHERE business_id = bid;
DELETE FROM business_hours WHERE business_id = bid;
DELETE FROM widget_settings  WHERE business_id = bid;
DELETE FROM payment_settings WHERE business_id = bid;

-- =============================================================
-- 3. BUSINESS HOURS
-- Mon–Fri 09:00–19:00 | Sat 10:00–17:00 | Sun closed
-- =============================================================
INSERT INTO business_hours (business_id, day_of_week, open_time, close_time, is_closed) VALUES
  (bid, 0, NULL,    NULL,    true),
  (bid, 1, '09:00', '19:00', false),
  (bid, 2, '09:00', '19:00', false),
  (bid, 3, '09:00', '19:00', false),
  (bid, 4, '09:00', '19:00', false),
  (bid, 5, '09:00', '19:00', false),
  (bid, 6, '10:00', '17:00', false);

-- =============================================================
-- 4. SERVICE CUSTOM FIELD DEFINITIONS
-- =============================================================
INSERT INTO service_custom_fields (business_id, label, field_key, input_type, options, is_required, sort_order) VALUES
  (bid, 'Downtime Required',     'downtime_required',     'dropdown', '["None","1-2 days","3-5 days","1 week","2+ weeks"]', false, 1),
  (bid, 'Numbing Included',      'numbing_included',      'checkbox', '[]', false, 2),
  (bid, 'Aftercare Instructions', 'aftercare_instructions','text',     '[]', false, 3);

-- =============================================================
-- 5. STAFF CUSTOM FIELD DEFINITIONS
-- =============================================================
INSERT INTO staff_custom_fields (business_id, label, field_key, input_type, options, is_required, sort_order) VALUES
  (bid, 'Board Certification',  'board_certification',  'text',     '[]', true,  1),
  (bid, 'Years of Experience',  'years_of_experience',  'number',   '[]', true,  2),
  (bid, 'Languages Spoken',     'languages_spoken',     'text',     '[]', false, 3),
  (bid, 'Accepting New Clients','accepting_new_clients','checkbox',  '[]', false, 4);

-- =============================================================
-- 6. WIDGET SETTINGS & APPEARANCE
-- =============================================================
DELETE FROM widget_appearance WHERE business_id = bid;

INSERT INTO widget_settings (business_id, welcome_message) VALUES
(
  bid,
  'Welcome to GlowUp Aesthetics! Ask us about Botox, fillers, skin treatments, or book a free consultation.'
);

INSERT INTO widget_appearance (business_id, primary_color) VALUES
(bid, '#a855f7');

-- =============================================================
-- 7. PAYMENT SETTINGS
-- =============================================================
INSERT INTO payment_settings (business_id, payment_type) VALUES
(bid, 'cash');

-- =============================================================
-- 8. STAFF (100 records)
-- =============================================================
INSERT INTO staff (business_id, name, role, bio, contact, is_active, meta) VALUES
(bid, 'Dr. Olivia Chen', 'Medical Director & Injector', 'Board-certified dermatologist and founder of GlowUp Aesthetics with 18 years of experience in cosmetic injectables and skin rejuvenation.', '{"email":"olivia.chen@glowup.com","phone":"+1 (310) 555-8801"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":18,"languages_spoken":"English, Mandarin","accepting_new_clients":true}'),
(bid, 'Dr. Marcus Rivera', 'Lead Injector', 'Fellowship-trained facial aesthetics specialist with expertise in advanced Botox techniques and facial contouring.', '{"email":"marcus.rivera@glowup.com","phone":"+1 (310) 555-8802"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":14,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. Priya Sharma', 'Cosmetic Dermatologist', 'Specializes in non-surgical facial rejuvenation, laser treatments, and customized skincare protocols.', '{"email":"priya.sharma@glowup.com","phone":"+1 (310) 555-8803"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":12,"languages_spoken":"English, Hindi","accepting_new_clients":true}'),
(bid, 'Dr. James Whitfield', 'Plastic Surgeon Consultant', 'Provides surgical consultations and performs advanced combination treatments alongside non-surgical procedures.', '{"email":"james.whitfield@glowup.com","phone":"+1 (310) 555-8804"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":20,"languages_spoken":"English","accepting_new_clients":false}'),
(bid, 'Dr. Yuki Tanaka', 'Aesthetic Medicine Physician', 'Expert in regenerative aesthetics including PRP therapy and mesotherapy with a precision-focused approach.', '{"email":"yuki.tanaka@glowup.com","phone":"+1 (310) 555-8805"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":9,"languages_spoken":"English, Japanese","accepting_new_clients":true}'),
(bid, 'Dr. Elena Vasquez', 'Senior Injector', 'Known for her signature natural-look technique in lip augmentation and mid-face volumizing.', '{"email":"elena.vasquez@glowup.com","phone":"+1 (310) 555-8806"}', true, '{"board_certification":"ABFM Family Medicine, Aesthetic Fellowship","years_of_experience":11,"languages_spoken":"English, Spanish, Portuguese","accepting_new_clients":true}'),
(bid, 'Dr. David Park', 'Laser Specialist', 'Dual board-certified physician focusing on laser skin resurfacing, scar revision, and pigmentation correction.', '{"email":"david.park@glowup.com","phone":"+1 (310) 555-8807"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":13,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'Dr. Aisha Okonkwo', 'Body Contouring Specialist', 'Expert in non-invasive body sculpting technologies including CoolSculpting and radiofrequency treatments.', '{"email":"aisha.okonkwo@glowup.com","phone":"+1 (310) 555-8808"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":8,"languages_spoken":"English, Yoruba","accepting_new_clients":true}'),
(bid, 'Dr. Robert Kline', 'Anti-Aging Specialist', 'Focuses on comprehensive anti-aging programs combining injectables, skin tightening, and hormone optimization.', '{"email":"robert.kline@glowup.com","phone":"+1 (310) 555-8809"}', true, '{"board_certification":"ABIM Internal Medicine, A4M Anti-Aging","years_of_experience":16,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Sophia Laurent', 'Facial Harmony Specialist', 'Trained in Paris and Beverly Hills, specializes in achieving balanced, proportionate facial aesthetics.', '{"email":"sophia.laurent@glowup.com","phone":"+1 (310) 555-8810"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":10,"languages_spoken":"English, French","accepting_new_clients":true}'),
(bid, 'NP Rachel Kim', 'Nurse Practitioner — Injectables', 'Board-certified NP with advanced injectable training and over 5,000 Botox treatments performed.', '{"email":"rachel.kim@glowup.com","phone":"+1 (310) 555-8811"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":7,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'NP Brandon Hayes', 'Nurse Practitioner — Skin', 'Specializes in chemical peels, microneedling, and medical-grade skincare consultations.', '{"email":"brandon.hayes@glowup.com","phone":"+1 (310) 555-8812"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":6,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'PA Jessica Torres', 'Physician Assistant — Aesthetics', 'Experienced PA performing dermal filler injections and skin rejuvenation treatments.', '{"email":"jessica.torres@glowup.com","phone":"+1 (310) 555-8813"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":5,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'RN Lisa Nguyen', 'Aesthetic Nurse — Laser', 'Certified laser technician with expertise in IPL, fractional CO2, and hair removal treatments.', '{"email":"lisa.nguyen@glowup.com","phone":"+1 (310) 555-8814"}', true, '{"board_certification":"CLT Certified Laser Technician","years_of_experience":8,"languages_spoken":"English, Vietnamese","accepting_new_clients":true}'),
(bid, 'RN Amanda Brooks', 'Aesthetic Nurse — Injectables', 'Skilled injectable nurse focusing on preventative Botox and natural lip enhancement.', '{"email":"amanda.brooks@glowup.com","phone":"+1 (310) 555-8815"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Michael Stern', 'Regenerative Medicine Physician', 'Pioneers stem cell and growth factor treatments for hair restoration and skin renewal.', '{"email":"michael.stern@glowup.com","phone":"+1 (310) 555-8816"}', true, '{"board_certification":"ABIM Internal Medicine","years_of_experience":15,"languages_spoken":"English, German","accepting_new_clients":true}'),
(bid, 'Dr. Caroline Dupont', 'Skin Health Director', 'Oversees all skin health programs including acne treatment, rosacea management, and pigmentation therapy.', '{"email":"caroline.dupont@glowup.com","phone":"+1 (310) 555-8817"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":11,"languages_spoken":"English, French","accepting_new_clients":true}'),
(bid, 'Dr. Ahmed Hassan', 'Facial Sculpting Specialist', 'Expert in jawline definition, chin augmentation, and non-surgical rhinoplasty using dermal fillers.', '{"email":"ahmed.hassan@glowup.com","phone":"+1 (310) 555-8818"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":9,"languages_spoken":"English, Arabic","accepting_new_clients":true}'),
(bid, 'Dr. Natasha Volkov', 'Laser & Skin Specialist', 'Internationally trained in laser medicine with specialization in melasma and ethnic skin treatments.', '{"email":"natasha.volkov@glowup.com","phone":"+1 (310) 555-8819"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":10,"languages_spoken":"English, Russian","accepting_new_clients":true}'),
(bid, 'Dr. Chris Morgan', 'Men''s Aesthetics Lead', 'Focuses exclusively on male facial aesthetics including Brotox, jawline sculpting, and hair restoration.', '{"email":"chris.morgan@glowup.com","phone":"+1 (310) 555-8820"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":7,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Diana Flores', 'Nurse Practitioner — Body', 'Specializes in body contouring, cellulite treatments, and post-surgical lymphatic drainage.', '{"email":"diana.flores@glowup.com","phone":"+1 (310) 555-8821"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":6,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'RN Kevin Walsh', 'Aesthetic Nurse — PRP', 'Certified in PRP therapy for hair restoration, under-eye rejuvenation, and skin regeneration.', '{"email":"kevin.walsh@glowup.com","phone":"+1 (310) 555-8822"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Maria Santos', 'Thread Lift Specialist', 'Pioneer of PDO thread techniques for non-surgical facelifts and neck tightening.', '{"email":"maria.santos@glowup.com","phone":"+1 (310) 555-8823"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":13,"languages_spoken":"English, Tagalog","accepting_new_clients":true}'),
(bid, 'Dr. Thomas Bell', 'Vein & Vascular Specialist', 'Treats spider veins, varicose veins, and vascular lesions using sclerotherapy and laser therapy.', '{"email":"thomas.bell@glowup.com","phone":"+1 (310) 555-8824"}', true, '{"board_certification":"ABVLM Vein Medicine","years_of_experience":14,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Hannah Lee', 'Microblading & PMU Artist', 'Medical-grade permanent makeup specialist for brows, lips, and eyeliner with over 3,000 procedures completed.', '{"email":"hannah.lee@glowup.com","phone":"+1 (310) 555-8825"}', true, '{"board_certification":"CPCP Certified Permanent Cosmetics","years_of_experience":8,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'PA Miguel Reyes', 'Physician Assistant — Injector', 'Expert in cheek volumizing, tear trough correction, and temple rejuvenation.', '{"email":"miguel.reyes@glowup.com","phone":"+1 (310) 555-8826"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":6,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. Grace Kim', 'Skin Rejuvenation Specialist', 'Combines microneedling, PRP, and medical peels for comprehensive skin renewal programs.', '{"email":"grace.kim@glowup.com","phone":"+1 (310) 555-8827"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":9,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'RN Stephanie Miller', 'CoolSculpting Technician', 'Certified CoolSculpting specialist with expertise in body contouring treatment planning.', '{"email":"stephanie.miller@glowup.com","phone":"+1 (310) 555-8828"}', true, '{"board_certification":"CSC CoolSculpting Certified","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Daniel Frost', 'Hair Restoration Surgeon', 'Board-certified surgeon specializing in FUE hair transplants and PRP hair therapy.', '{"email":"daniel.frost@glowup.com","phone":"+1 (310) 555-8829"}', true, '{"board_certification":"ABHRS Hair Restoration Surgery","years_of_experience":12,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Carla Jenkins', 'Nurse Practitioner — Wellness', 'Manages IV vitamin therapy, hormone optimization, and weight management programs.', '{"email":"carla.jenkins@glowup.com","phone":"+1 (310) 555-8830"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":7,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Alex Petrov', 'Scar Revision Specialist', 'Treats acne scars, surgical scars, and keloids using fractional lasers and subcision techniques.', '{"email":"alex.petrov@glowup.com","phone":"+1 (310) 555-8831"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":10,"languages_spoken":"English, Russian","accepting_new_clients":true}'),
(bid, 'RN Monica Vega', 'Chemical Peel Specialist', 'Expert in superficial, medium, and deep chemical peels for anti-aging and pigmentation.', '{"email":"monica.vega@glowup.com","phone":"+1 (310) 555-8832"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":6,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. William Chang', 'Non-Surgical Rhinoplasty Expert', 'Performs liquid nose jobs using hyaluronic acid fillers with an artistic, detail-oriented approach.', '{"email":"william.chang@glowup.com","phone":"+1 (310) 555-8833"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":11,"languages_spoken":"English, Cantonese","accepting_new_clients":true}'),
(bid, 'PA Brittany Cole', 'Physician Assistant — Skin', 'Focuses on acne treatment protocols, rosacea management, and post-procedure skincare.', '{"email":"brittany.cole@glowup.com","phone":"+1 (310) 555-8834"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Sarah Blackwell', 'Hyperhidrosis Specialist', 'Treats excessive sweating with Botox injections and miraDry technology.', '{"email":"sarah.blackwell@glowup.com","phone":"+1 (310) 555-8835"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":8,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Omar Farid', 'Lip Augmentation Expert', 'Renowned for his signature lip enhancement technique achieving natural, balanced results.', '{"email":"omar.farid@glowup.com","phone":"+1 (310) 555-8836"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":10,"languages_spoken":"English, Arabic, French","accepting_new_clients":true}'),
(bid, 'RN Tiffany Dean', 'Hydrafacial Specialist', 'Certified HydraFacial provider with expertise in customized facial protocols for all skin types.', '{"email":"tiffany.dean@glowup.com","phone":"+1 (310) 555-8837"}', true, '{"board_certification":"HFS HydraFacial Specialist","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Lucas Martin', 'Platelet-Rich Plasma Specialist', 'Uses PRP exclusively for facial rejuvenation, hair regrowth, and sexual wellness treatments.', '{"email":"lucas.martin@glowup.com","phone":"+1 (310) 555-8838"}', true, '{"board_certification":"ABIM Internal Medicine","years_of_experience":9,"languages_spoken":"English, French","accepting_new_clients":true}'),
(bid, 'NP Sandra Olson', 'Nurse Practitioner — Anti-Aging', 'Develops personalized anti-aging treatment plans combining injectables and skin therapies.', '{"email":"sandra.olson@glowup.com","phone":"+1 (310) 555-8839"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":8,"languages_spoken":"English, Swedish","accepting_new_clients":true}'),
(bid, 'Dr. Nina Patel', 'Pigmentation & Melasma Expert', 'Dermatologist specializing in hyperpigmentation, melasma, and ethnic skin concerns.', '{"email":"nina.patel@glowup.com","phone":"+1 (310) 555-8840"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":11,"languages_spoken":"English, Gujarati, Hindi","accepting_new_clients":true}'),
(bid, 'RN Jason Cruz', 'Aesthetic Nurse — Sculptra', 'Specializes in Sculptra biostimulator treatments for gradual collagen restoration.', '{"email":"jason.cruz@glowup.com","phone":"+1 (310) 555-8841"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":5,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. Rebecca Woods', 'Vaginal Rejuvenation Specialist', 'Provides non-surgical intimate wellness treatments using radiofrequency and laser technology.', '{"email":"rebecca.woods@glowup.com","phone":"+1 (310) 555-8842"}', true, '{"board_certification":"ABOG OB/GYN","years_of_experience":14,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Peter Johansson', 'RF Skin Tightening Specialist', 'Expert in radiofrequency treatments including Morpheus8, Thermage, and Exilis for skin laxity.', '{"email":"peter.johansson@glowup.com","phone":"+1 (310) 555-8843"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":10,"languages_spoken":"English, Swedish","accepting_new_clients":true}'),
(bid, 'PA Lauren Mitchell', 'Physician Assistant — Fillers', 'Focuses on mid-face volumizing, cheek enhancement, and hand rejuvenation with fillers.', '{"email":"lauren.mitchell@glowup.com","phone":"+1 (310) 555-8844"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'RN Christine Adler', 'Microneedling Specialist', 'Expert in microneedling with PRP, Morpheus8, and collagen induction therapy.', '{"email":"christine.adler@glowup.com","phone":"+1 (310) 555-8845"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":6,"languages_spoken":"English, German","accepting_new_clients":true}'),
(bid, 'Dr. Ryan Foster', 'Weight Management Physician', 'Oversees medical weight loss programs including Semaglutide and Tirzepatide protocols.', '{"email":"ryan.foster@glowup.com","phone":"+1 (310) 555-8846"}', true, '{"board_certification":"ABOM Obesity Medicine","years_of_experience":8,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Emily Watson', 'Nurse Practitioner — IV Therapy', 'Administers IV vitamin drips, NAD+ infusions, and glutathione treatments for wellness.', '{"email":"emily.watson@glowup.com","phone":"+1 (310) 555-8847"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Isabella Romano', 'Eyelid & Periorbital Specialist', 'Non-surgical expert in under-eye treatments, brow lifts, and periorbital rejuvenation.', '{"email":"isabella.romano@glowup.com","phone":"+1 (310) 555-8848"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":12,"languages_spoken":"English, Italian","accepting_new_clients":true}'),
(bid, 'RN Derek Sullivan', 'Tattoo Removal Specialist', 'Operates PicoSure and Q-switched lasers for tattoo removal and pigmented lesion treatment.', '{"email":"derek.sullivan@glowup.com","phone":"+1 (310) 555-8849"}', true, '{"board_certification":"CLT Certified Laser Technician","years_of_experience":7,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Helen Park', 'PDO Thread Specialist', 'Specializes in barb, smooth, and screw PDO threads for face and neck lifting.', '{"email":"helen.park@glowup.com","phone":"+1 (310) 555-8850"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":9,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'Dr. Benjamin Cruz', 'Full-Face Rejuvenation Expert', 'Creates comprehensive treatment plans addressing all facial zones for harmonious results.', '{"email":"benjamin.cruz@glowup.com","phone":"+1 (310) 555-8851"}', false, '{"board_certification":"ABDS Dermatology","years_of_experience":15,"languages_spoken":"English, Spanish","accepting_new_clients":false}'),
(bid, 'PA Andrea Brown', 'Physician Assistant — Laser', 'Performs laser hair removal, vein treatment, and skin resurfacing procedures.', '{"email":"andrea.brown@glowup.com","phone":"+1 (310) 555-8852"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Jordan Blake', 'Nurse Practitioner — Men''s Health', 'Provides men''s aesthetic treatments and testosterone optimization programs.', '{"email":"jordan.blake@glowup.com","phone":"+1 (310) 555-8853"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":6,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Michelle Liu', 'Acne & Scar Treatment Lead', 'Treats active acne and acne scarring with a combination of lasers, peels, and injectables.', '{"email":"michelle.liu@glowup.com","phone":"+1 (310) 555-8854"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":10,"languages_spoken":"English, Mandarin","accepting_new_clients":true}'),
(bid, 'RN Patricia Green', 'Aesthetic Nurse — Kybella', 'Specializes in Kybella injections for submental fat reduction and jawline definition.', '{"email":"patricia.green@glowup.com","phone":"+1 (310) 555-8855"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Anthony Russo', 'Hand & Décolletage Specialist', 'Rejuvenates hands and chest using fillers, lasers, and chemical peels.', '{"email":"anthony.russo@glowup.com","phone":"+1 (310) 555-8856"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":11,"languages_spoken":"English, Italian","accepting_new_clients":true}'),
(bid, 'Dr. Fatima Al-Rashid', 'Halal Aesthetics Consultant', 'Provides culturally sensitive aesthetic consultations and treatments.', '{"email":"fatima.alrashid@glowup.com","phone":"+1 (310) 555-8857"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":8,"languages_spoken":"English, Arabic, Farsi","accepting_new_clients":true}'),
(bid, 'NP Heather Ross', 'Nurse Practitioner — Skin Health', 'Medical-grade skincare consultations and customized treatment protocols.', '{"email":"heather.ross@glowup.com","phone":"+1 (310) 555-8858"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":7,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'RN Taylor Swift', 'Aesthetic Nurse — Peels', 'Performs medical-grade chemical peels ranging from lunchtime peels to deep resurfacing.', '{"email":"taylor.swift@glowup.com","phone":"+1 (310) 555-8859"}', false, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":3,"languages_spoken":"English","accepting_new_clients":false}'),
(bid, 'Dr. Raj Kapoor', 'Ultrasound Skin Lifting Expert', 'Specializes in Ultherapy and HIFU treatments for non-surgical facelifts.', '{"email":"raj.kapoor@glowup.com","phone":"+1 (310) 555-8860"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":12,"languages_spoken":"English, Hindi, Punjabi","accepting_new_clients":true}'),
(bid, 'PA Nathan Clarke', 'Physician Assistant — Body', 'Performs body contouring assessments and non-invasive fat reduction treatments.', '{"email":"nathan.clarke@glowup.com","phone":"+1 (310) 555-8861"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Lena Fischer', 'European Skincare Specialist', 'Brings German precision to facial treatments with a focus on barrier repair and hydration.', '{"email":"lena.fischer@glowup.com","phone":"+1 (310) 555-8862"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":9,"languages_spoken":"English, German","accepting_new_clients":true}'),
(bid, 'RN Angela Park', 'LED Light Therapy Specialist', 'Certified in phototherapy treatments for acne, inflammation, and collagen stimulation.', '{"email":"angela.park@glowup.com","phone":"+1 (310) 555-8863"}', true, '{"board_certification":"CLT Certified Light Therapist","years_of_experience":4,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'Dr. Victor Mendez', 'Scalp Micropigmentation Artist', 'Creates natural-looking hairline restorations using advanced micropigmentation techniques.', '{"email":"victor.mendez@glowup.com","phone":"+1 (310) 555-8864"}', true, '{"board_certification":"CPCP Certified Permanent Cosmetics","years_of_experience":7,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'NP Karen Young', 'Nurse Practitioner — Hormones', 'Bioidentical hormone replacement therapy and metabolic health optimization.', '{"email":"karen.young@glowup.com","phone":"+1 (310) 555-8865"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":9,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Samuel Obi', 'Dark Skin Aesthetics Expert', 'Specializes in safe and effective aesthetic treatments for Fitzpatrick types IV-VI.', '{"email":"samuel.obi@glowup.com","phone":"+1 (310) 555-8866"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":11,"languages_spoken":"English, Igbo","accepting_new_clients":true}'),
(bid, 'RN Megan Hart', 'Dermaplaning Specialist', 'Expert in dermaplaning, oxygen facials, and combination skin resurfacing treatments.', '{"email":"megan.hart@glowup.com","phone":"+1 (310) 555-8867"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Julia Stone', 'Combination Therapy Director', 'Designs multi-modality treatment plans combining energy devices, injectables, and topicals.', '{"email":"julia.stone@glowup.com","phone":"+1 (310) 555-8868"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":14,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'PA Richard Gomez', 'Physician Assistant — Wellness', 'Manages vitamin injections, weight loss protocols, and preventative health screenings.', '{"email":"richard.gomez@glowup.com","phone":"+1 (310) 555-8869"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":6,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. Catherine White', 'Neck & Jawline Specialist', 'Expert in neck rejuvenation, platysmal band treatment, and jawline contouring.', '{"email":"catherine.white@glowup.com","phone":"+1 (310) 555-8870"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":13,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Vanessa Reed', 'Nurse Practitioner — Regenerative', 'Performs exosome therapy, stem cell treatments, and regenerative skin procedures.', '{"email":"vanessa.reed@glowup.com","phone":"+1 (310) 555-8871"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":6,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Ian Cooper', 'Skin Cancer Screening Lead', 'Provides full-body skin checks, mole mapping, and early detection screenings.', '{"email":"ian.cooper@glowup.com","phone":"+1 (310) 555-8872"}', false, '{"board_certification":"ABDS Dermatology","years_of_experience":17,"languages_spoken":"English","accepting_new_clients":false}'),
(bid, 'RN Danielle Fox', 'Lymphatic Drainage Specialist', 'Certified in manual lymphatic drainage and post-procedure recovery treatments.', '{"email":"danielle.fox@glowup.com","phone":"+1 (310) 555-8873"}', true, '{"board_certification":"CMLDT Certified Manual Lymphatic Drainage","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. George Nakamura', 'Asian Aesthetics Specialist', 'Tailors treatments for Asian facial features including double eyelid and V-line contouring.', '{"email":"george.nakamura@glowup.com","phone":"+1 (310) 555-8874"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":13,"languages_spoken":"English, Japanese","accepting_new_clients":true}'),
(bid, 'PA Samantha Pierce', 'Physician Assistant — Peels', 'Specializes in chemical peel formulations and post-peel skincare management.', '{"email":"samantha.pierce@glowup.com","phone":"+1 (310) 555-8875"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Erik Lindberg', 'Cryotherapy Specialist', 'Performs cryotherapy treatments for skin lesions, fat reduction, and recovery.', '{"email":"erik.lindberg@glowup.com","phone":"+1 (310) 555-8876"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":8,"languages_spoken":"English, Swedish, Norwegian","accepting_new_clients":true}'),
(bid, 'NP Chloe Adams', 'Nurse Practitioner — Lashes & Brows', 'Provides lash lifts, brow lamination, and growth serum prescriptions.', '{"email":"chloe.adams@glowup.com","phone":"+1 (310) 555-8877"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":3,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Philip Grant', 'Vascular Laser Expert', 'Treats rosacea, broken capillaries, and port wine stains using pulsed-dye and Nd:YAG lasers.', '{"email":"philip.grant@glowup.com","phone":"+1 (310) 555-8878"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":12,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'RN Brooke Nelson', 'Aesthetic Nurse — Wellness', 'Administers B12, biotin, and collagen-boosting injection treatments.', '{"email":"brooke.nelson@glowup.com","phone":"+1 (310) 555-8879"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Claudia Hernandez', 'Stretch Mark Treatment Expert', 'Uses lasers, microneedling, and PRP for stretch mark and scar improvement.', '{"email":"claudia.hernandez@glowup.com","phone":"+1 (310) 555-8880"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":9,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'PA Derek Young', 'Physician Assistant — Hair', 'Manages non-surgical hair restoration programs and PRP scalp treatments.', '{"email":"derek.young@glowup.com","phone":"+1 (310) 555-8881"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Anna Kowalski', 'Medical Tattoo Artist', 'Performs areola restoration, scar camouflage, and vitiligo micropigmentation.', '{"email":"anna.kowalski@glowup.com","phone":"+1 (310) 555-8882"}', true, '{"board_certification":"CPCP Certified Permanent Cosmetics","years_of_experience":10,"languages_spoken":"English, Polish","accepting_new_clients":true}'),
(bid, 'NP Justin Lee', 'Nurse Practitioner — Sexual Wellness', 'Provides PRP intimate treatments and hormone optimization for sexual health.', '{"email":"justin.lee@glowup.com","phone":"+1 (310) 555-8883"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":6,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Irene Christou', 'Skin Barrier Specialist', 'Treats sensitive, reactive, and compromised skin conditions with evidence-based protocols.', '{"email":"irene.christou@glowup.com","phone":"+1 (310) 555-8884"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":8,"languages_spoken":"English, Greek","accepting_new_clients":true}'),
(bid, 'RN Carlos Diaz', 'Aesthetic Nurse — RF', 'Operates Morpheus8, Vivace, and EndyMed radiofrequency devices for skin tightening.', '{"email":"carlos.diaz@glowup.com","phone":"+1 (310) 555-8885"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":5,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. Raymond Kwon', 'Under-Eye Specialist', 'Expert in tear trough fillers, dark circle treatments, and periorbital rejuvenation.', '{"email":"raymond.kwon@glowup.com","phone":"+1 (310) 555-8886"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":10,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'PA Ashley Turner', 'Physician Assistant — Injectables', 'Performs jawline, chin, and cheek filler treatments with a focus on facial balance.', '{"email":"ashley.turner@glowup.com","phone":"+1 (310) 555-8887"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Maxwell Hughes', 'Anti-Aging Research Director', 'Leads clinical trials and implements cutting-edge longevity and anti-aging therapies.', '{"email":"maxwell.hughes@glowup.com","phone":"+1 (310) 555-8888"}', false, '{"board_certification":"ABIM Internal Medicine","years_of_experience":22,"languages_spoken":"English","accepting_new_clients":false}'),
(bid, 'NP Olivia Santos', 'Nurse Practitioner — Injectables', 'High-volume injector performing Botox and filler treatments with a gentle touch.', '{"email":"olivia.santos@glowup.com","phone":"+1 (310) 555-8889"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":5,"languages_spoken":"English, Portuguese","accepting_new_clients":true}'),
(bid, 'RN Amy Richardson', 'Pre & Post Care Coordinator', 'Manages patient preparation and recovery protocols for all aesthetic procedures.', '{"email":"amy.richardson@glowup.com","phone":"+1 (310) 555-8890"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":6,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Steven Gold', 'Celebrity Injector', 'Discreet, high-end injectable specialist with an exclusive Beverly Hills clientele.', '{"email":"steven.gold@glowup.com","phone":"+1 (310) 555-8891"}', true, '{"board_certification":"ABPS Plastic Surgery","years_of_experience":19,"languages_spoken":"English","accepting_new_clients":false}'),
(bid, 'Dr. Laura Bennett', 'Hormonal Skin Specialist', 'Treats hormonal acne, menopausal skin changes, and PCOS-related skin conditions.', '{"email":"laura.bennett@glowup.com","phone":"+1 (310) 555-8892"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":10,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'PA Tyler Morrison', 'Physician Assistant — Laser Hair', 'Specializes in laser hair removal for all skin types using multi-wavelength technology.', '{"email":"tyler.morrison@glowup.com","phone":"+1 (310) 555-8893"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":5,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Rosa Martinez', 'Nurse Practitioner — Scar Treatment', 'Combines subcision, fillers, and lasers for comprehensive acne scar revision.', '{"email":"rosa.martinez@glowup.com","phone":"+1 (310) 555-8894"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":7,"languages_spoken":"English, Spanish","accepting_new_clients":true}'),
(bid, 'Dr. Kenneth Zhao', 'Medical Spa Director', 'Oversees all clinical operations, staff training, and treatment protocol development.', '{"email":"kenneth.zhao@glowup.com","phone":"+1 (310) 555-8895"}', true, '{"board_certification":"ABDS Dermatology","years_of_experience":16,"languages_spoken":"English, Mandarin","accepting_new_clients":false}'),
(bid, 'RN Hannah Grey', 'Aesthetic Nurse — Facials', 'Performs medical-grade facials including enzyme treatments, LED therapy, and extractions.', '{"email":"hannah.grey@glowup.com","phone":"+1 (310) 555-8896"}', true, '{"board_certification":"CANS Certified Aesthetic Nurse","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'Dr. Vincent Tao', 'Combination Injectable Artist', 'Creates full-face transformations combining neurotoxins, fillers, and biostimulators.', '{"email":"vincent.tao@glowup.com","phone":"+1 (310) 555-8897"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":11,"languages_spoken":"English, Mandarin, Cantonese","accepting_new_clients":true}'),
(bid, 'PA Chelsea Wright', 'Physician Assistant — Skin Checks', 'Performs dermoscopic skin examinations and assists with minor excisions.', '{"email":"chelsea.wright@glowup.com","phone":"+1 (310) 555-8898"}', true, '{"board_certification":"NCCPA Physician Assistant","years_of_experience":4,"languages_spoken":"English","accepting_new_clients":true}'),
(bid, 'NP Douglas Kim', 'Nurse Practitioner — Biostimulators', 'Expert in Sculptra, Radiesse, and Ellanse for long-lasting collagen stimulation.', '{"email":"douglas.kim@glowup.com","phone":"+1 (310) 555-8899"}', true, '{"board_certification":"AANP Nurse Practitioner","years_of_experience":6,"languages_spoken":"English, Korean","accepting_new_clients":true}'),
(bid, 'Dr. Gabrielle Moreau', 'French Aesthetic Physician', 'Brings refined European injection techniques emphasizing subtlety and elegance.', '{"email":"gabrielle.moreau@glowup.com","phone":"+1 (310) 555-8900"}', true, '{"board_certification":"AAAM Aesthetic Medicine","years_of_experience":13,"languages_spoken":"English, French","accepting_new_clients":true}');

-- =============================================================
-- 9. SERVICES (100 records)
-- =============================================================
INSERT INTO services (business_id, name, description, price, duration_minutes, category, is_active, staff_ids, meta) VALUES
-- Botox / Neurotoxins (1-15)
(bid, 'Botox — Forehead Lines', 'Smooths horizontal forehead lines with precise Botox injections. Results last 3-4 months.', 250.00, 30, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Avoid lying down for 4 hours. No exercise for 24 hours."}'),
(bid, 'Botox — Frown Lines (Glabellar)', 'Targets the "11" lines between the eyebrows for a refreshed, approachable look.', 275.00, 30, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Do not rub the treated area. Results visible in 3-7 days."}'),
(bid, 'Botox — Crow''s Feet', 'Softens fine lines around the eyes that appear when smiling or squinting.', 225.00, 20, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Avoid makeup on treated area for 4 hours."}'),
(bid, 'Botox — Full Upper Face', 'Comprehensive treatment of forehead, frown lines, and crow''s feet in one session.', 650.00, 45, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Stay upright for 4 hours. Avoid strenuous exercise for 24 hours."}'),
(bid, 'Botox — Bunny Lines', 'Smooths wrinkles on the sides of the nose that appear when scrunching.', 150.00, 15, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"No rubbing or massaging the nose area."}'),
(bid, 'Botox — Lip Flip', 'Subtle enhancement that relaxes the upper lip to create a fuller appearance without filler.', 175.00, 15, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Avoid using straws for 48 hours. Results appear in 5-7 days."}'),
(bid, 'Botox — Chin Dimpling', 'Relaxes the mentalis muscle to smooth a dimpled or pebbled chin texture.', 150.00, 15, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Minimal aftercare needed. Avoid touching treated area."}'),
(bid, 'Botox — Gummy Smile Correction', 'Reduces excessive gum display when smiling by relaxing the upper lip elevator muscles.', 200.00, 20, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"May feel mild tightness. Results in 5-10 days."}'),
(bid, 'Botox — Jawline Slimming (Masseter)', 'Reduces jaw width by relaxing the masseter muscles for a slimmer facial profile.', 450.00, 30, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Avoid chewing gum for 2 weeks. Full results in 4-6 weeks."}'),
(bid, 'Botox — Neck Bands (Platysma)', 'Smooths vertical neck bands for a more youthful neck and jawline appearance.', 350.00, 30, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Avoid neck exercises for 48 hours."}'),
(bid, 'Botox — Hyperhidrosis (Underarms)', 'Treats excessive underarm sweating with Botox injections. Results last 6-9 months.', 900.00, 45, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":true,"aftercare_instructions":"Avoid antiperspirant for 24 hours. No exercise day of treatment."}'),
(bid, 'Botox — Hyperhidrosis (Palms)', 'Reduces excessive palm sweating for improved confidence and comfort.', 1000.00, 60, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Temporary hand weakness possible. Avoid gripping heavy objects for 48 hours."}'),
(bid, 'Dysport — Full Upper Face', 'Alternative neurotoxin that spreads naturally for a softer, more diffused result.', 600.00, 45, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Same aftercare as Botox. Results may appear 1-2 days faster than Botox."}'),
(bid, 'Xeomin — Forehead & Frown Lines', 'Pure neurotoxin without complexing proteins. Ideal for patients who have developed tolerance.', 500.00, 30, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Same aftercare as Botox. Great option for Botox-resistant patients."}'),
(bid, 'Preventative Botox (Under 30)', 'Low-dose Botox for younger patients to prevent wrinkle formation before they set in.', 200.00, 20, 'Botox & Neurotoxins', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Maintain treatment every 4-5 months for best prevention."}'),

-- Dermal Fillers (16-30)
(bid, 'Lip Filler — Natural Enhancement', 'Subtle lip augmentation using hyaluronic acid filler for a naturally fuller pout. 1 syringe.', 550.00, 45, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Ice lips for 10 minutes every hour. Avoid kissing and straws for 48 hours."}'),
(bid, 'Lip Filler — Full Volume', 'Dramatic lip volumizing using 2 syringes for a plump, defined lip shape.', 1000.00, 60, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Significant swelling expected for 48-72 hours. Sleep elevated."}'),
(bid, 'Cheek Filler — Volume Restoration', 'Restores youthful cheek volume and lifts mid-face sagging. 1-2 syringes.', 750.00, 45, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid sleeping on your side for 2 nights. Mild bruising normal."}'),
(bid, 'Jawline Filler — Definition', 'Creates a sharper, more defined jawline using structured hyaluronic acid filler.', 800.00, 45, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid clenching jaw. No dental work for 2 weeks."}'),
(bid, 'Chin Filler — Projection', 'Adds chin projection and balances the facial profile without surgery.', 650.00, 30, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid touching chin area. Sleep on back for 2 nights."}'),
(bid, 'Tear Trough Filler (Under-Eye)', 'Corrects dark hollows under the eyes for a rested, refreshed appearance. Cannula technique.', 700.00, 45, 'Dermal Fillers', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Significant bruising possible. Arnica recommended. No blood thinners 1 week prior."}'),
(bid, 'Nasolabial Fold Filler', 'Softens deep smile lines running from nose to mouth. 1-2 syringes.', 600.00, 30, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid excessive facial expressions for 24 hours."}'),
(bid, 'Marionette Line Filler', 'Fills the lines running from mouth corners downward to reduce a sad or aged appearance.', 600.00, 30, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid wide mouth movements for 24 hours."}'),
(bid, 'Non-Surgical Rhinoplasty', 'Reshapes the nose using filler to smooth bumps, lift the tip, or improve symmetry.', 850.00, 45, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Do not wear glasses for 2 weeks. Avoid pressure on nose."}'),
(bid, 'Temple Filler', 'Restores volume to hollowed temples for a more youthful facial frame.', 650.00, 30, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid headbands and tight hats for 1 week."}'),
(bid, 'Hand Rejuvenation Filler', 'Plumps the backs of hands to hide veins and tendons for a youthful appearance.', 700.00, 30, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Avoid heavy lifting for 48 hours. Wear sunscreen on hands."}'),
(bid, 'Earlobe Rejuvenation Filler', 'Restores volume to thinning earlobes and corrects elongated piercing holes.', 400.00, 20, 'Dermal Fillers', true, '[]', '{"downtime_required":"None","numbing_included":true,"aftercare_instructions":"Avoid wearing heavy earrings for 2 weeks."}'),
(bid, 'Filler Dissolving (Hyaluronidase)', 'Dissolves previously placed hyaluronic acid filler that has migrated or is unwanted.', 350.00, 30, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":false,"aftercare_instructions":"Swelling expected. Wait 2 weeks before re-injecting filler."}'),
(bid, 'Full Face Filler Package', 'Comprehensive facial balancing using 4-6 syringes across multiple areas.', 2800.00, 90, 'Dermal Fillers', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Bruising and swelling expected. Plan for social downtime."}'),
(bid, 'Radiesse — Cheeks & Jawline', 'Calcium-based filler providing structure plus collagen stimulation. Lasts 12-18 months.', 750.00, 45, 'Dermal Fillers', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Cannot be dissolved. Avoid massage of treated area."}'),

-- Skin Treatments (31-50)
(bid, 'HydraFacial — Classic', 'Three-step cleanse, exfoliate, and hydrate facial using patented vortex technology.', 175.00, 45, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Apply SPF. Skin will glow immediately. No harsh actives for 48 hours."}'),
(bid, 'HydraFacial — Deluxe', 'Enhanced HydraFacial with LED light therapy, lymphatic drainage, and boosters.', 275.00, 60, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Same as classic. Extra hydration recommended."}'),
(bid, 'Chemical Peel — Light (Lunchtime)', 'Gentle glycolic or lactic acid peel for brightness and texture. No downtime.', 150.00, 30, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"SPF mandatory. Avoid retinol for 3 days."}'),
(bid, 'Chemical Peel — Medium (TCA)', 'Trichloroacetic acid peel targeting fine lines, sun damage, and pigmentation.', 300.00, 45, 'Skin Treatments', true, '[]', '{"downtime_required":"3-5 days","numbing_included":false,"aftercare_instructions":"Peeling starts day 3. Do not pick. Moisturize frequently."}'),
(bid, 'Chemical Peel — Deep (Phenol)', 'Strongest peel for deep wrinkles, severe sun damage, and scarring.', 800.00, 90, 'Skin Treatments', true, '[]', '{"downtime_required":"2+ weeks","numbing_included":true,"aftercare_instructions":"Significant peeling and redness. Follow strict aftercare protocol provided."}'),
(bid, 'Microneedling — Standard', 'Collagen induction therapy using fine needles to improve texture, scars, and pores.', 300.00, 60, 'Skin Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Redness like sunburn for 24-48 hours. No makeup for 24 hours."}'),
(bid, 'Microneedling with PRP', 'Microneedling combined with platelet-rich plasma for enhanced healing and rejuvenation.', 500.00, 75, 'Skin Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Leave PRP on skin for 8 hours. No washing face until next morning."}'),
(bid, 'Morpheus8 — Face', 'Radiofrequency microneedling for deep skin remodeling, tightening, and scar revision.', 900.00, 60, 'Skin Treatments', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Grid marks and redness for 3-5 days. Avoid sun exposure."}'),
(bid, 'Morpheus8 — Body', 'RF microneedling for stretch marks, cellulite, and body skin tightening.', 1200.00, 90, 'Skin Treatments', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Wear compression garment if treating abdomen. Redness for 3-5 days."}'),
(bid, 'Dermaplaning', 'Manual exfoliation removing dead skin cells and peach fuzz for a smooth, glowing complexion.', 125.00, 30, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"SPF required. Skin will be more sensitive to sun."}'),
(bid, 'Oxygen Facial', 'Pressurized oxygen delivers serums deep into skin for instant hydration and radiance.', 200.00, 45, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Perfect before events. No special aftercare needed."}'),
(bid, 'LED Light Therapy — Red', 'Red LED wavelengths stimulate collagen production and reduce inflammation.', 75.00, 20, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Can be done weekly. No aftercare required."}'),
(bid, 'LED Light Therapy — Blue', 'Blue LED wavelengths kill acne-causing bacteria and calm active breakouts.', 75.00, 20, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Combine with skincare routine for best results."}'),
(bid, 'Vampire Facial (PRP Facial)', 'PRP applied topically after microneedling for the ultimate skin regeneration treatment.', 600.00, 75, 'Skin Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Bloody appearance normal initially. Do not wash for 8 hours."}'),
(bid, 'Acne Treatment Package (6 sessions)', 'Comprehensive acne program with peels, extractions, LED, and home care guidance.', 900.00, 60, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Follow prescribed skincare routine between sessions."}'),
(bid, 'Brightening Vitamin C Infusion Facial', 'Clinical-strength vitamin C treatment targeting dark spots, dullness, and uneven tone.', 225.00, 50, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Apply SPF 50. Avoid AHA/BHA for 48 hours."}'),
(bid, 'Back Facial & Acne Treatment', 'Deep cleansing, exfoliation, and extractions for back acne (bacne) and congestion.', 200.00, 60, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Wear loose clothing. Avoid hot showers for 12 hours."}'),
(bid, 'Hydrating Collagen Mask Treatment', 'Intensive hydration facial with collagen sheet mask, hyaluronic acid, and peptide serums.', 150.00, 45, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Skip retinol tonight. Enjoy your glow."}'),
(bid, 'Pigmentation Correction Treatment', 'Targeted treatment for melasma, sun spots, and post-inflammatory hyperpigmentation.', 350.00, 60, 'Skin Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":false,"aftercare_instructions":"Strict sun avoidance. SPF 50 reapplied every 2 hours."}'),

-- Laser Treatments (51-65)
(bid, 'Laser Hair Removal — Small Area', 'Permanent hair reduction for upper lip, chin, underarms, or bikini line.', 150.00, 20, 'Laser Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"No sun exposure before or after. Shave, never wax between sessions."}'),
(bid, 'Laser Hair Removal — Medium Area', 'Permanent hair reduction for half arms, half legs, or full bikini.', 300.00, 40, 'Laser Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"6-8 sessions needed. Treat every 4-6 weeks."}'),
(bid, 'Laser Hair Removal — Large Area', 'Permanent hair reduction for full legs, full back, or chest.', 500.00, 60, 'Laser Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Shedding occurs 1-3 weeks after treatment. Exfoliate gently."}'),
(bid, 'Laser Hair Removal — Full Body', 'Complete body hair removal session covering all major areas.', 1200.00, 120, 'Laser Treatments', true, '[]', '{"downtime_required":"None","numbing_included":true,"aftercare_instructions":"Redness and bumps normal for 24-48 hours. Aloe vera recommended."}'),
(bid, 'Fractional CO2 Laser — Face', 'Ablative laser resurfacing for deep wrinkles, acne scars, and sun damage.', 1500.00, 60, 'Laser Treatments', true, '[]', '{"downtime_required":"1 week","numbing_included":true,"aftercare_instructions":"Intense redness and peeling for 7-10 days. Keep skin moist. No sun."}'),
(bid, 'Fractional CO2 Laser — Neck', 'Laser resurfacing of the neck for crepey skin, lines, and sun damage.', 800.00, 45, 'Laser Treatments', true, '[]', '{"downtime_required":"1 week","numbing_included":true,"aftercare_instructions":"Same as face. Neck heals slightly slower."}'),
(bid, 'IPL Photofacial', 'Intense pulsed light targeting brown spots, redness, and broken capillaries.', 350.00, 30, 'Laser Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":false,"aftercare_instructions":"Dark spots will darken then flake off in 7-10 days. SPF required."}'),
(bid, 'Laser Tattoo Removal — Small', 'PicoSure laser for breaking down tattoo ink on small tattoos (under 4 sq inches).', 250.00, 20, 'Laser Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Blistering normal. Keep covered with ointment. 6-10 sessions typical."}'),
(bid, 'Laser Tattoo Removal — Large', 'PicoSure laser treatment for medium to large tattoos.', 500.00, 45, 'Laser Treatments', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"More intense healing. Follow wound care protocol. Sessions every 6-8 weeks."}'),
(bid, 'Laser Vein Treatment (Spider Veins)', 'Nd:YAG laser treatment for spider veins on legs or face.', 300.00, 30, 'Laser Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Wear compression stockings for 48 hours. Walk daily."}'),
(bid, 'Laser Skin Tightening (Titan)', 'Non-ablative infrared laser for skin tightening on face, neck, or abdomen.', 600.00, 45, 'Laser Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"No downtime. 3-5 sessions recommended for optimal results."}'),
(bid, 'Pulsed Dye Laser — Rosacea', 'Gold-standard laser for treating rosacea redness and visible blood vessels.', 400.00, 30, 'Laser Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":false,"aftercare_instructions":"Purpura (bruising) possible for 7-10 days. Avoid heat and alcohol."}'),
(bid, 'Erbium Laser Resurfacing', 'Precise ablative laser for fine lines, texture, and superficial scarring.', 1000.00, 45, 'Laser Treatments', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Less downtime than CO2. Redness for 3-5 days."}'),
(bid, 'Laser Stretch Mark Treatment', 'Fractional laser combined with RF to improve the color and texture of stretch marks.', 450.00, 45, 'Laser Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"3-6 sessions needed. Keep treated area moisturized."}'),
(bid, 'BBL (BroadBand Light) Therapy', 'Advanced IPL technology for sun damage, age spots, and overall skin rejuvenation.', 400.00, 30, 'Laser Treatments', true, '[]', '{"downtime_required":"1-2 days","numbing_included":false,"aftercare_instructions":"Coffee ground spots will flake off. Strict SPF for 4 weeks."}'),

-- Body Contouring (66-75)
(bid, 'CoolSculpting — Single Area', 'Non-invasive fat freezing to permanently reduce stubborn fat pockets.', 750.00, 60, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Numbness and tingling normal for 2 weeks. Results visible in 2-3 months."}'),
(bid, 'CoolSculpting — Abdomen Package', 'Comprehensive abdominal sculpting treating upper, lower, and flanks.', 2500.00, 180, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Massage treated areas daily. Wear comfortable clothing."}'),
(bid, 'Kybella — Double Chin (1 vial)', 'Injectable fat dissolving treatment for submental fullness (double chin).', 600.00, 30, 'Body Contouring', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Significant swelling for 3-5 days (frog neck). Ice frequently."}'),
(bid, 'Kybella — Double Chin (3-vial package)', 'Three-treatment Kybella series for optimal double chin reduction.', 1500.00, 30, 'Body Contouring', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Each session 6-8 weeks apart. Swelling decreases with subsequent sessions."}'),
(bid, 'RF Body Tightening — Abdomen', 'Radiofrequency treatment to tighten loose abdominal skin post-weight loss or pregnancy.', 500.00, 60, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Stay hydrated. 4-6 sessions recommended."}'),
(bid, 'RF Body Tightening — Arms', 'Tightens loose skin on upper arms (bat wings) using radiofrequency energy.', 400.00, 45, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Mild redness for a few hours. No special aftercare."}'),
(bid, 'Emsculpt NEO — Abdomen', 'Simultaneous fat burning and muscle building using HIFEM+ and RF technology.', 1000.00, 30, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Feels like an intense workout. Soreness normal. 4 sessions recommended."}'),
(bid, 'Emsculpt NEO — Buttocks', 'Non-invasive butt lift by building gluteal muscle and reducing fat.', 1000.00, 30, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Equivalent to 20,000 squats per session. Soreness expected."}'),
(bid, 'Cellulite Treatment — QWO', 'FDA-approved injectable for moderate to severe cellulite on buttocks.', 850.00, 30, 'Body Contouring', true, '[]', '{"downtime_required":"1-2 days","numbing_included":false,"aftercare_instructions":"Bruising and soreness at injection sites for 7-10 days."}'),
(bid, 'Sclerotherapy — Spider Veins (Legs)', 'Injection treatment to collapse and eliminate spider veins on legs.', 350.00, 30, 'Body Contouring', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Wear compression stockings for 3 days. Walk 30 minutes daily."}'),

-- Thread Lifts (76-80)
(bid, 'PDO Thread Lift — Mid-Face', 'Non-surgical facelift using PDO barb threads to lift sagging cheeks and jowls.', 2000.00, 60, 'Thread Lifts', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"No wide mouth opening for 2 weeks. Sleep on back. Avoid facials for 4 weeks."}'),
(bid, 'PDO Thread Lift — Jawline', 'Defines and tightens the jawline using dissolvable PDO threads.', 1500.00, 45, 'Thread Lifts', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Mild pulling sensation normal. Results improve over 3 months."}'),
(bid, 'PDO Thread Lift — Neck', 'Lifts and tightens neck skin using barbed PDO threads for a smoother neckline.', 1800.00, 60, 'Thread Lifts', true, '[]', '{"downtime_required":"3-5 days","numbing_included":true,"aftercare_instructions":"Avoid turning head sharply. Sleep elevated for 1 week."}'),
(bid, 'PDO Thread Lift — Brow', 'Subtle brow lift using smooth PDO threads to open and elevate the eye area.', 1200.00, 30, 'Thread Lifts', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Mild swelling around brow. Avoid rubbing eyes."}'),
(bid, 'Smooth Thread Skin Rejuvenation', 'Mesh of smooth PDO threads placed under skin to stimulate collagen and improve texture.', 800.00, 45, 'Thread Lifts', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Treats fine lines and crepey skin. Results build over 3-6 months."}'),

-- Biostimulators (81-85)
(bid, 'Sculptra — Full Face (1 vial)', 'Poly-L-lactic acid biostimulator that gradually rebuilds lost collagen over months.', 850.00, 45, 'Biostimulators', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Massage 5 times daily for 5 days in 5 areas (5-5-5 rule)."}'),
(bid, 'Sculptra — Full Face (3-vial package)', 'Complete Sculptra program with 3 sessions spaced 6 weeks apart for optimal collagen rebuild.', 2200.00, 45, 'Biostimulators', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Follow 5-5-5 massage rule. Final results at 6 months."}'),
(bid, 'Sculptra — Buttocks (BBL Alternative)', 'Non-surgical butt enhancement using Sculptra to add volume and lift.', 3500.00, 90, 'Biostimulators', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"Massage buttocks area as directed. Avoid sitting for prolonged periods day 1."}'),
(bid, 'Hyperdilute Radiesse — Skin Quality', 'Diluted calcium hydroxylapatite injected superficially for skin tightening and quality improvement.', 700.00, 45, 'Biostimulators', true, '[]', '{"downtime_required":"None","numbing_included":true,"aftercare_instructions":"Treats neck, décolletage, arms, and knees. Results build gradually."}'),
(bid, 'Profhilo — Bio-Remodeling', 'Ultra-pure hyaluronic acid injected at 5 bio-aesthetic points to hydrate and tighten skin.', 650.00, 30, 'Biostimulators', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"2 sessions 4 weeks apart. Avoid makeup for 6 hours."}'),

-- Hair Restoration (86-90)
(bid, 'PRP Hair Restoration — Scalp', 'Platelet-rich plasma injections into the scalp to stimulate hair follicle growth.', 750.00, 45, 'Hair Restoration', true, '[]', '{"downtime_required":"None","numbing_included":true,"aftercare_instructions":"No washing hair for 24 hours. Avoid hats for 48 hours. Monthly for 3 months."}'),
(bid, 'PRP Hair Restoration — 3-Session Package', 'Three monthly PRP scalp treatments for optimal hair regrowth results.', 1900.00, 45, 'Hair Restoration', true, '[]', '{"downtime_required":"None","numbing_included":true,"aftercare_instructions":"Results visible at 3-6 months. Maintenance every 6 months."}'),
(bid, 'Scalp Micropigmentation', 'Medical tattooing that replicates the appearance of hair follicles for thinning areas.', 1500.00, 120, 'Hair Restoration', true, '[]', '{"downtime_required":"1-2 days","numbing_included":true,"aftercare_instructions":"No washing scalp for 4 days. Avoid swimming and sun for 1 month. 2-3 sessions needed."}'),
(bid, 'Low-Level Laser Therapy (LLLT) Hair', 'Red light therapy cap sessions to stimulate hair follicle activity and reduce shedding.', 100.00, 30, 'Hair Restoration', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Consistent use 3x/week for 6 months for best results."}'),
(bid, 'Hair Growth Consultation', 'Comprehensive scalp analysis with trichoscopy and personalized hair restoration plan.', 150.00, 45, 'Hair Restoration', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Blood work may be ordered. Follow recommended treatment plan."}'),

-- Wellness & IV Therapy (91-95)
(bid, 'IV Vitamin Drip — Beauty Glow', 'Biotin, glutathione, and vitamin C IV drip for skin radiance and hair/nail health.', 250.00, 45, 'Wellness & IV Therapy', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Stay hydrated. May feel energized. Can repeat weekly."}'),
(bid, 'IV Vitamin Drip — Immune Boost', 'High-dose vitamin C, zinc, and B-complex drip for immune system support.', 225.00, 45, 'Wellness & IV Therapy', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Great before travel or during cold season."}'),
(bid, 'IV Vitamin Drip — Recovery & Energy', 'B12, magnesium, and amino acid drip for post-workout recovery and energy.', 275.00, 60, 'Wellness & IV Therapy', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Hydrate well. Optimal with regular exercise routine."}'),
(bid, 'NAD+ IV Infusion', 'Nicotinamide adenine dinucleotide infusion for cellular repair, anti-aging, and mental clarity.', 500.00, 120, 'Wellness & IV Therapy', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"May feel flushing or chest tightness during infusion (normal). Slow drip."}'),
(bid, 'Glutathione IV Push', 'Master antioxidant injection for skin brightening, detoxification, and liver support.', 150.00, 15, 'Wellness & IV Therapy', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Best results with weekly treatments for 8-12 weeks."}'),

-- Consultations & Other (96-100)
(bid, 'Free Aesthetic Consultation', 'Complimentary 30-minute consultation to discuss your aesthetic goals and treatment options.', 0.00, 30, 'Consultations', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Bring a list of current medications and any questions."}'),
(bid, 'Medical Skincare Consultation', 'In-depth skin analysis with VISIA imaging and customized medical-grade skincare prescription.', 100.00, 45, 'Consultations', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Follow prescribed skincare routine. Follow-up in 6 weeks."}'),
(bid, 'Virtual Aesthetic Consultation', 'Remote video consultation to discuss goals, review photos, and plan your treatment journey.', 75.00, 30, 'Consultations', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Have well-lit photos ready. Treatment plan emailed within 24 hours."}'),
(bid, 'Semaglutide Weight Loss Program (Monthly)', 'FDA-approved GLP-1 injection for medical weight management with monthly check-ins.', 500.00, 30, 'Weight Management', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Inject weekly as directed. Nausea may occur initially. Stay hydrated."}'),
(bid, 'Post-Procedure Recovery Facial', 'Gentle, soothing facial designed for post-laser, post-peel, or post-injectable recovery.', 125.00, 30, 'Skin Treatments', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Ultra-gentle products only. No actives."}'),
(bid, 'Annual Skin Health Membership', 'Includes monthly HydraFacial, quarterly peel, 10% off injectables, and priority booking.', 2400.00, 30, 'Memberships', true, '[]', '{"downtime_required":"None","numbing_included":false,"aftercare_instructions":"Membership auto-renews. Cancel anytime with 30 days notice."}');

END $$;
